export const NORMAL_RANGES: Record<string, { min: number; max: number; unit: string }> = {
  fasting_glucose:   { min: 70,   max: 100,  unit: 'mg/dL' },
  postmeal_glucose:  { min: 0,    max: 140,  unit: 'mg/dL' },
  systolic_bp:       { min: 90,   max: 120,  unit: 'mmHg' },
  diastolic_bp:      { min: 60,   max: 80,   unit: 'mmHg' },
  pulse:             { min: 60,   max: 100,  unit: 'bpm' },
  total_cholesterol: { min: 0,    max: 200,  unit: 'mg/dL' },
  hdl:               { min: 40,   max: 999,  unit: 'mg/dL' },
  ldl:               { min: 0,    max: 130,  unit: 'mg/dL' },
  triglycerides:     { min: 0,    max: 150,  unit: 'mg/dL' },
  creatinine:        { min: 0.7,  max: 1.3,  unit: 'mg/dL' },
  egfr:              { min: 60,   max: 999,  unit: 'mL/min' },
  got_ast:           { min: 0,    max: 40,   unit: 'U/L' },
  gpt_alt:           { min: 0,    max: 40,   unit: 'U/L' },
  hemoglobin:        { min: 12,   max: 16,   unit: 'g/dL' },
  wbc:               { min: 4,    max: 10,   unit: '10³/μL' },
  hba1c:             { min: 0,    max: 5.7,  unit: '%' },
  uric_acid:         { min: 2.5,  max: 7.0,  unit: 'mg/dL' },
  bmi:               { min: 18.5, max: 24,   unit: 'kg/m²' },
};
